name: Hello World Actions
on: [push]
jobs: 
    hello-world-actions:
      runs-on: ubuntu-latest
      steps:
            - run: echo "Hello World!!!"
            - run: echo "Ya tengo hambre"
            - run: echo "Quiero comer tacos"
            - name: crea unos archivos
              run: touch file1.txt
            - name: guarda el listado de archivos
              run: ls -al > filel.txt
            - run: echo "Agrego una linea a file2.txt" >> file2.txt
            - run: cat file2.txt
            - run: ls -al

